Controllers/CountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WalmartInventory.Data;
using WalmartInventory.Models;

namespace WalmartInventory.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class CountsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CountsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Counts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Counts.ToListAsync());
        }

        // GET: Counts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var count = await _context.Counts
                .FirstOrDefaultAsync(m => m.CountId == id);
            if (count == null)
            {
                return NotFound();
            }

            return View(count);
        }

        // GET: Counts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Counts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CountId,ManagerId,userNumber,departName,countTotal")] Count count)
        {
            if (ModelState.IsValid)
            {
                _context.Add(count);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(count);
        }

        // GET: Counts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var count = await _context.Counts.FindAsync(id);
            if (count == null)
            {
                return NotFound();
            }
            return View(count);
        }

        // POST: Counts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CountId,ManagerId,userNumber,departName,countTotal")] Count count)
        {
            if (id != count.CountId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(count);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CountExists(count.CountId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(count);
        }

        // GET: Counts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var count = await _context.Counts
                .FirstOrDefaultAsync(m => m.CountId == id);
            if (count == null)
            {
                return NotFound();
            }

            return View(count);
        }

        // POST: Counts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var count = await _context.Counts.FindAsync(id);
            _context.Counts.Remove(count);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CountExists(int id)
        {
            return _context.Counts.Any(e => e.CountId == id);
        }
    }
}

Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WalmartInventory.Data;
using WalmartInventory.Models;

namespace WalmartInventory.Controllers
{
    public class ItemsController : Controller
    {

        private readonly ApplicationDbContext _context;

        public ItemsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            // get the list of products that i wat to show in the main page
            // get the list of departmet that i wat to show in the main page

            var department = _context.Departments.OrderBy(p => p.Name).ToList();
            return View(department);
        }

        public IActionResult Browse(int id)
        {
            //this query is to get the product by selected departmet
            var products = _context.Products.Where(p => p.DepartmentId == id).OrderBy(p => p.Name).ToList();

            //to show the selected department

            ViewBag.department = _context.Departments.Find(id).Name.ToString();
            return View(products);
        }

        public IActionResult AddToCart(int ProductId, int Quantity)
        {
            // to get the product price
            var price = _context.Products.Find(ProductId).RetailPrice;

            //to get current time and date
            var currentTimeDate = DateTime.Now;

            //EmployeeId variable
            var EmployeeId = GetEmployeeId();

            // e

            //to make new cart create and save object
            var cart = new ShoppingCart
            {
                ProductId = ProductId,
                Quantity = Quantity,
                Price = price,
                DateSelected = currentTimeDate,
                EmployeeId = EmployeeId


            };

            _context.ShoppingCarts.Add(cart);
            _context.SaveChanges();


            // here we return to cart view
            return RedirectToAction("Cart");
        }

        private string GetEmployeeId()
        {
            
            if(HttpContext.Session.GetString("EmployeeId") == null)
            {
                // check if the Employee is logged in, if there is no existing EmpId
                var EmployeeId = "";
                
                //to make the use of email as employee id, when logged in
                if (User.Identity.IsAuthenticated)
                {
                    EmployeeId = User.Identity.Name;

                    // here name is the email used
                }

                // but if user is anonymous, use the guid to create ew identifier
                else
                {
                    EmployeeId = Guid.NewGuid().ToString();
                }

                //now put the emp id in a session variable
                HttpContext.Session.SetString("EmployeeId", EmployeeId);
            }

            // here we return the Session variable

            return HttpContext.Session.GetString("EmployeeId");

        }

        //item/cart
        public IActionResult Cart()
        {

            // getting the current cart to show
            var EmployeeId = "";

            //if user is in cart page but havent add anything, here idetify them first
            if (HttpContext.Session.GetString("EmployeeId") == null)
            {
                EmployeeId = GetEmployeeId();

            }
            else
            {
                EmployeeId = HttpContext.Session.GetString("EmployeeId");
            }
            //to show 

            var cartItems = _context.ShoppingCarts.Where(e => e.EmployeeId == EmployeeId).ToList();

            //passing the data to view
            return View(cartItems);

            //.Include(e => e.Product)
        }
    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WalmartInventory.Data;
using WalmartInventory.Models;

namespace WalmartInventory.Controllers
{
    [Authorize(Roles = "Administrator, Customer")]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Products.Include(p => p.Department);
            return View(await applicationDbContext.ToListAsync());
        }

        [AllowAnonymous]
        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Department)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "Name");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,DepartmentId,Name,ShelfName,RetailPrice")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "Name", product.DepartmentId);
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "Name", product.DepartmentId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,DepartmentId,Name,ShelfName,RetailPrice")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "Name", product.DepartmentId);
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Department)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WalmartInventory</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow  font-italic text-primary">
            <div class="container font-weight-bold ">
                <a class="navbar-brand navbar-brand-logo" >

                    <div class="logo">
                        <img src="https://invitationdigital-res-1.cloudinary.com/image/upload/w_165,h_165,q_auto,fl_strip_profile,f_auto/Venues_W_Walmart_5100_walmart_logo.jpg" />
                    </div>
                </a>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WalmartInventory</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="sec h5">
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>*@

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Index">Items</a>
                            </li>



                            @if (User.IsInRole("Customer"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Product</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Index">Department</a>
                                </li>
                            }
                            @if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Product</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Index">Department</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Counts" asp-action="Index">Count</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="CountInformations" asp-action="Index">CountInformation</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container ">
       
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
       

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Kulpreet - 200439805 - COMP2084 <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>